### ISSUE TITLE
dotnet-watch for MSBuild fails: "InvalidOperationException: Sequence contains no matching element"

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/DotNetTools#230]
dotnet-watch 1.0.0-msbuild1-final fails for all usages with the following error:

```
System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at Microsoft.DotNet.Watcher.Internal.MsBuildFileSetFactory.FindWatchTargetsDir()
   at Microsoft.DotNet.Watcher.Internal.MsBuildFileSetFactory..ctor(ILogger logger, String projectFile, OutputSink outputSink)
   at Microsoft.DotNet.Watcher.Program.<MainInternalAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.DotNet.Watcher.Program.Main(String[] args)
[DotNetWatcher] An unexpected error occurred
```

Using dotnet-cli 1.0.0-preview3-004056
```xml
<DotNetCliToolReference Include="Microsoft.DotNet.Watcher.Tools" Version="1.0.0-msbuild1-final" />
```

**Comment by natemcmaster** [comment]
This is the result of missing the .targets files in the nupkg. 

**Workaround**
Extract the *.targets files from the zip link below into *%USERPROFILE%/.nuget/packages/microsoft.dotnet.watcher.tools/1.0.0-msbuild1-final/tools/*.

[dotnet-watch-targets.zip](https://github.com/aspnet/DotNetTools/files/596030/dotnet-watch.zip). This includes the targets files from https://github.com/aspnet/DotNetTools/tree/rel/1.0.0-msbuild1/src/Microsoft.DotNet.Watcher.Tools/tools.

**Comment by natemcmaster** [comment]
To fix this, we have pushed an update to nuget.org. Users should upgrade to [`1.0.0-msbuild1-update1`](https://www.nuget.org/packages/Microsoft.DotNet.Watcher.Tools/1.0.0-msbuild1-update1).
