### ISSUE TITLE
[Flaky test] ProgramTests.ConsoleCancelKey 

### ISSUE THREAD

**Issue by pranavkm** [aspnet/DotNetTools#288]
```
System.TimeoutException : Task exceeded max running time of 30s at C:\BuildAgent\work\2b0c8ce712895332\.r\DotNetTools\test\Microsoft.DotNet.Watcher.Tools.Tests\ProgramTests.cs:42
   at System.Threading.Tasks.TaskExtensions.<OrTimeout>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.TaskExtensions.<OrTimeout>d__0`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.DotNet.Watcher.Tools.Tests.ProgramTests.<ConsoleCancelKey>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

**Comment by pranavkm** [comment]
Failed build instance: http://aspnetci/viewLog.html?buildId=210275&tab=buildResultsDiv&buildTypeId=XPlat_Windows_Win2008r2_Universe
