### ISSUE TITLE
System.UnauthorizedAccessException error when calling dotnet user-secrets -h

### ISSUE THREAD

**Issue by tylerd** [aspnet/DotNetTools#317]
Using VS Code, embedded command line terminal

```
.NET Command Line Tools (2.1.0-preview1-006632)

Product Information:
 Version:            2.1.0-preview1-006632
 Commit SHA-1 hash:  5c67b11d62

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.0-preview1-006632\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview3-25428-01
  Build    : ac5794cad4e07620d21cbc6eca6d070ada99a2cd
```
Project File
`<DotNetCliToolReference Include="Microsoft.Extensions.SecretManager.Tools" Version="2.0.0-preview2-final" />`

## Error
```
System.UnauthorizedAccessException: Access to the path 'C:\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.extensions.secretmanager.tools\2.0.0-preview2-final\lib\netcoreapp2.0\dotnet-user
-secrets.runtimeconfig.json' is denied.
   at System.IO.FileStream.OpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode)
   at Microsoft.DotNet.Cli.Utils.RuntimeConfig..ctor(String runtimeConfigPath)
   at Microsoft.DotNet.Cli.Utils.PackagedCommandSpecFactoryWithCliRuntime.AddAditionalParameters(String commandPath, IList`1 arguments)
   at Microsoft.DotNet.Cli.Utils.PackagedCommandSpecFactory.CreatePackageCommandSpecUsingMuxer(String commandPath, IEnumerable`1 commandArguments, String depsFilePath, CommandResolutionStrategy c
ommandResolutionStrategy, IEnumerable`1 packageFolders, String runtimeConfigPath)
   at Microsoft.DotNet.Cli.Utils.PackagedCommandSpecFactory.CreateCommandSpecWrappingWithMuxerIfDll(String commandPath, IEnumerable`1 commandArguments, String depsFilePath, CommandResolutionStrat
egy commandResolutionStrategy, IEnumerable`1 packageFolders, String runtimeConfigPath)
   at Microsoft.DotNet.Cli.Utils.PackagedCommandSpecFactory.CreateCommandSpecFromLibrary(LockFileTargetLibrary toolLibrary, String commandName, IEnumerable`1 commandArguments, IEnumerable`1 allow
edExtensions, LockFile lockFile, CommandResolutionStrategy commandResolutionStrategy, String depsFilePath, String runtimeConfigPath)
   at Microsoft.DotNet.Cli.Utils.ProjectToolsCommandResolver.ResolveCommandSpecFromToolLibrary(SingleProjectInfo toolLibraryRange, String commandName, IEnumerable`1 args, IProject project)
   at Microsoft.DotNet.Cli.Utils.ProjectToolsCommandResolver.ResolveCommandSpecFromAllToolLibraries(IEnumerable`1 toolsLibraries, String commandName, IEnumerable`1 args, IProject project)
   at Microsoft.DotNet.Cli.Utils.ProjectToolsCommandResolver.ResolveFromProjectTools(CommandResolverArguments commandResolverArguments)
   at Microsoft.DotNet.Cli.Utils.ProjectToolsCommandResolver.Resolve(CommandResolverArguments commandResolverArguments)
   at Microsoft.DotNet.Cli.Utils.CompositeCommandResolver.Resolve(CommandResolverArguments commandResolverArguments)
   at Microsoft.DotNet.Cli.Utils.CommandResolver.TryResolveCommandSpec(ICommandResolverPolicy commandResolverPolicy, String commandName, IEnumerable`1 args, NuGetFramework framework, String confi
guration, String outputPath, String applicationName)
   at Microsoft.DotNet.Cli.Utils.Command.Create(ICommandResolverPolicy commandResolverPolicy, String commandName, IEnumerable`1 args, NuGetFramework framework, String configuration, String output
Path, String applicationName)
   at Microsoft.DotNet.Cli.Utils.Command.Create(String commandName, IEnumerable`1 args, NuGetFramework framework, String configuration, String outputPath, String applicationName)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
```

**Comment by tylerd** [comment]
It looks like this is related
https://github.com/dotnet/cli/issues/7034

**Comment by natemcmaster** [comment]
Yup, it's the same issue dotnet/cli#7034. Closing as a duplicate.
