### ISSUE TITLE
GenerateSSLCertificateTaskTest fails on macOS with "AppleCommonCryptoCryptographicException : User interaction is not allowed."

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/DotNetTools#332]
http://aspnetci/viewLog.html?buildId=302410&tab=buildResultsDiv&buildTypeId=XPlat_Mac_MacUniverseCoreCLR

```
Interop+AppleCrypto+AppleCommonCryptoCryptographicException : User interaction is not allowed.
   at Interop.AppleCrypto.X509StoreAddCertificate(SafeKeychainItemHandle certOrIdentity, SafeKeychainHandle keychain)
   at Internal.Cryptography.Pal.StorePal.AppleKeychainStore.Add(ICertificatePal cert)
   at System.Security.Cryptography.X509Certificates.X509Store.Add(X509Certificate2 certificate)
   at Microsoft.AspNetCore.CertificateGeneration.Task.GenerateSSLCertificateTaskTest.CreateCertificate(DateTimeOffset notBefore, DateTimeOffset expires, Boolean savePrivateKey) in /Users/asplab/TeamCity/work/33bdfc1cae7b2a38/.r/DotNetTools/test/Microsoft.AspNetcore.CertificateGeneration.Task.Tests/GenerateSSLCertificateTaskTest.cs:line 210
   at Microsoft.AspNetCore.CertificateGeneration.Task.GenerateSSLCertificateTaskTest.GenerateSSLCertificateTaskTest_CreatesCertificate_IfFoundCertificateIsNotYetValid() in /Users/asplab/TeamCity/work/33bdfc1cae7b2a38/.r/DotNetTools/test/Microsoft.AspNetcore.CertificateGeneration.Task.Tests/GenerateSSLCertificateTaskTest.cs:line 62
```

cc @javiercn

**Comment by natemcmaster** [comment]
Closing as a duplicate of https://github.com/dotnet/corefx/issues/20324. Apparently, rebooting the machine makes this go away, though we don't know why.
