### ISSUE TITLE
Flaky test AppWithDepsTests.ChangeFileInDependency 

### ISSUE THREAD

**Issue by pranavkm** [aspnet/DotNetTools#336]
```
System.TimeoutException : Task exceeded max running time of 30s at C:\b\w\d6337ac2abf63a4b\.repositories\DotNetTools\test\Microsoft.DotNet.Watcher.Tools.FunctionalTests\AppWithDepsTests.cs:24
   at System.Threading.Tasks.TaskExtensions.<OrTimeout>d__1.MoveNext() in C:\b\w\d6337ac2abf63a4b\.repositories\DotNetTools\test\Microsoft.DotNet.Watcher.Tools.Tests\Utilities\TaskExtensions.cs:line 27
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.DotNet.Watcher.Tools.FunctionalTests.AppWithDepsTests.<ChangeFileInDependency>d__2.MoveNext() in C:\b\w\d6337ac2abf63a4b\.repositories\DotNetTools\test\Microsoft.DotNet.Watcher.Tools.FunctionalTests\AppWithDepsTests.cs:line 24
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

**Comment by pranavkm** [comment]
cc @natemcmaster \ @Eilon 

Could we fix \ disable the test? We haven't updated the runtime so it's unlikely we're running in to a new issue.

**Comment by natemcmaster** [comment]
This is a weird regression. Here is the error produced within the "dotnet-build" executed in the test.
```
Process exited 1980
Process exited 1980 with code 0
Building AppWithDeps
Project directory: 'C:\b\w\d6337ac2abf63a4b\.repositories\DotNetTools\testWorkDir\fb749415b9614031b47f4bf2a742df24\work\AppWithDeps'
Started process 2856: C:\b\w\d6337ac2abf63a4b\.build\dotnet\dotnet.exe build
Microsoft (R) Build Engine version 15.1.548.43366
Copyright (C) Microsoft Corporation. All rights reserved.

  Dependency -> C:\b\w\d6337ac2abf63a4b\.repositories\DotNetTools\testWorkDir\fb749415b9614031b47f4bf2a742df24\work\Dependency\bin\Release\netstandard1.5\Dependency.dll
CSC : error CS2012: Cannot open 'C:\b\w\d6337ac2abf63a4b\.repositories\DotNetTools\testWorkDir\fb749415b9614031b47f4bf2a742df24\work\AppWithDeps\obj\Release\netcoreapp1.0\AppWithDeps.dll' for writing -- 'Could not find a part of the path 'C:\b\w\d6337ac2abf63a4b\.repositories\DotNetTools\testWorkDir\fb749415b9614031b47f4bf2a742df24\work\AppWithDeps\obj\Release\netcoreapp1.0\AppWithDeps.dll'.' [C:\b\w\d6337ac2abf63a4b\.repositories\DotNetTools\testWorkDir\fb749415b9614031b47f4bf2a742df24\work\AppWithDeps\AppWithDeps.csproj]
C:\b\w\d6337ac2abf63a4b\.build\dotnet\sdk\1.0.1\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.Sdk.targets(92,5): error MSB4018: The "GenerateDepsFile" task failed unexpectedly. [C:\b\w\d6337ac2abf63a4b\.repositories\DotNetTools\testWorkDir\fb749415b9614031b47f4bf2a742df24\work\AppWithDeps\AppWithDeps.csproj]
C:\b\w\d6337ac2abf63a4b\.build\dotnet\sdk\1.0.1\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.Sdk.targets(92,5): error MSB4018: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\b\w\d6337ac2abf63a4b\.repositories\DotNetTools\testWorkDir\fb749415b9614031b47f4bf2a742df24\work\AppWithDeps\bin\Release\netcoreapp1.0\AppWithDeps.deps.json'. [C:\b\w\d6337ac2abf63a4b\.repositories\DotNetTools\testWorkDir\fb749415b9614031b47f4bf2a742df24\work\AppWithDeps\AppWithDeps.csproj]
C:\b\w\d6337ac2abf63a4b\.build\dotnet\sdk\1.0.1\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.Sdk.targets(92,5): error MSB4018:    at System.IO.Win32FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, FileStream parent) [C:\b\w\d6337ac2abf63a4b\.repositories\DotNetTools\testWorkDir\fb749415b9614031b47f4bf2a742df24\work\AppWithDeps\AppWithDeps.csproj]
C:\b\w\d6337ac2abf63a4b\.build\dotnet\sdk\1.0.1\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.Sdk.targets(92,5): error MSB4018:    at System.IO.Win32FileSystem.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, FileStream parent) [C:\b\w\d6337ac2abf63a4b\.repositories\DotNetTools\testWorkDir\fb749415b9614031b47f4bf2a742df24\work\AppWithDeps\AppWithDeps.csproj]
C:\b\w\d6337ac2abf63a4b\.build\dotnet\sdk\1.0.1\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.Sdk.targets(92,5): error MSB4018:    at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options) [C:\b\w\d6337ac2abf63a4b\.repositories\DotNetTools\testWorkDir\fb749415b9614031b47f4bf2a742df24\work\AppWithDeps\AppWithDeps.csproj]
C:\b\w\d6337ac2abf63a4b\.build\dotnet\sdk\1.0.1\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.Sdk.targets(92,5): error MSB4018:    at Microsoft.NET.Build.Tasks.GenerateDepsFile.ExecuteCore() [C:\b\w\d6337ac2abf63a4b\.repositories\DotNetTools\testWorkDir\fb749415b9614031b47f4bf2a742df24\work\AppWithDeps\AppWithDeps.csproj]
C:\b\w\d6337ac2abf63a4b\.build\dotnet\sdk\1.0.1\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.Sdk.targets(92,5): error MSB4018:    at Microsoft.NET.Build.Tasks.TaskBase.Execute() [C:\b\w\d6337ac2abf63a4b\.repositories\DotNetTools\testWorkDir\fb749415b9614031b47f4bf2a742df24\work\AppWithDeps\AppWithDeps.csproj]
C:\b\w\d6337ac2abf63a4b\.build\dotnet\sdk\1.0.1\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.Sdk.targets(92,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() [C:\b\w\d6337ac2abf63a4b\.repositories\DotNetTools\testWorkDir\fb749415b9614031b47f4bf2a742df24\work\AppWithDeps\AppWithDeps.csproj]
C:\b\w\d6337ac2abf63a4b\.build\dotnet\sdk\1.0.1\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.Sdk.targets(92,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__25.MoveNext() [C:\b\w\d6337ac2abf63a4b\.repositories\DotNetTools\testWorkDir\fb749415b9614031b47f4bf2a742df24\work\AppWithDeps\AppWithDeps.csproj]

Build FAILED.
```

**Comment by natemcmaster** [comment]
This one went away with a rebuild. Maybe it was a weird file permissions error? We'll re-open if it happens again.

Also, we increased the timeout so dotnet-restore being slow shouldn't cause more failures. See #337. Leaving open for now so I can port that change to dev as well.

**Comment by natemcmaster** [comment]
Still flaky in dev
