### ISSUE TITLE
Missing assembly in Docker container

### ISSUE THREAD

**Issue by fogzot** [aspnet/DotNetTools#364]
While trying to replicate the dotnet-watch + Docker configuration found on http://www.natemcmaster.com/blog/2017/11/13/dotnet-watch-and-docker/ with a simple web application (on Linux) I get the following error while trying to run `dotnet watch run`:

```
Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'System.ComponentModel.Primitives, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider.CreateFileWatcher(String root)
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider..ctor(String root)
   at Microsoft.Extensions.Configuration.FileConfigurationExtensions.SetBasePath(IConfigurationBuilder builder, String basePath)
   at DesignViewer.Program.CreateWebHostBuilder(String[] args)
   at DesignViewer.Program.Main(String[] args)
watch : Exited with error code 134
```

This happens only if the `obj` and `bin` directories are moved to `..` as explained in the post. If they are left in the project top-level directory everything works but, obviously, this doesn't work when mixed with something outside Docker (like VS Code that needs `obj`/`bin` for intellisense).

I am using the stock `dotnet watch` 2.0.0.

Edit: forgot to tag @natemcmaster .

**Comment by fogzot** [comment]
I just wanted to add that I get exactly the same error with 2.1.0-preview1-27567:

```
root@076fbf6f0771:/app/source# dotnet watch run --no-restore
watch : Polling file watcher is enabled
watch : Started

Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'System.ComponentModel.Primitives, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider.CreateFileWatcher(String root)
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider..ctor(String root)
   at Microsoft.Extensions.Configuration.FileConfigurationExtensions.SetBasePath(IConfigurationBuilder builder, String basePath)
   at DesignViewer.Program.CreateWebHostBuilder(String[] args)
   at DesignViewer.Program.Main(String[] args)
watch : Exited with error code 134
```

**Comment by natemcmaster** [comment]
> This happens only if the obj and bin directories are moved to .. as explained in the post. 

How did you configure this?

**Comment by fogzot** [comment]
Here is the full `.csproj` file.

```
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <EnableDefaultItems>false</EnableDefaultItems>
    <BaseIntermediateOutputPath>$(MSBuildProjectDirectory)\..\obj\</BaseIntermediateOutputPath>
    <BaseOutputPath>$(MSBuildProjectDirectory)\..\bin\</BaseOutputPath>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="src\**\*.cs"/>
    <EmbeddedResource Include="src\**\*.resx"/>
    <Content Include="wwwroot\**" CopyToPublishDirectory="PreserveNewest"/>
    <Content Include="src\**\*.cshtml" CopyToPublishDirectory="PreserveNewest"/>
    <Content Include="appsettings*.json" CopyToPublishDirectory="PreserveNewest"/>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Routing" Version="2.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.StaticFiles" Version="2.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.HttpOverrides" Version="2.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.Cors" Version="2.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="2.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.Identity" Version="2.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics" Version="2.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.Server.Kestrel" Version="2.0.1" />
    <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="2.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="2.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.CommandLine" Version="2.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="2.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="2.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="2.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Configuration" Version="2.0.0" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="2.0.0" />
    <PackageReference Include="Npgsql" Version="3.2.5" />
    <PackageReference Include="MimeKit" Version="1.20.0" />
    <PackageReference Include="MailKit" Version="1.20.0" />
    <PackageReference Include="Dndg.Gluon" Version="1.99.2" />
    <PackageReference Include="Dndg.Gluon.Npgsql" Version="1.99.2" />
    <PackageReference Include="Dndg.Gluon.AspNetCore" Version="1.99.2" />
  </ItemGroup>
  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.DotNet.Watcher.Tools" Version="2.0.0" />
    <DotNetCliToolReference Include="Dndg.Gluon.Tools" Version="1.99.2" />
  </ItemGroup>
</Project>
```

**Comment by natemcmaster** [comment]
You most likely ran into this: https://github.com/Microsoft/msbuild/issues/1603. Try setting BaseIntermediateOutputPath and BaseOutputPath from a file named Directory.Build.props, as mentioned in [the post](http://www.natemcmaster.com/blog/2017/11/13/dotnet-watch-and-docker/#change-the-location-of--the-obj-and-bin-folders). When using the implicit top/bottom imports (i.e. `<Project Sdk="Microsoft.NET.Sdk.Web">`, your project settings are set _after_ the import of Microsoft.Common.props. By using Directory.Build.props, these are set _before_ Microsoft.Common.props.

**Comment by fogzot** [comment]
I understand. Thank you for the clarification.

**Comment by natemcmaster** [comment]
Did that fix the issue for you?

**Comment by fogzot** [comment]
Yes, it works. I had an issue because I forgot to use version 2.1.0-preview1-27567 for the watch tool but after fixing that everything works. Thank you very much and sorry for the noise.

**Comment by natemcmaster** [comment]
No worries. Happy to help.
