### ISSUE TITLE
Flaky test: MultipleTriggers

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/DotNetTools#409]
This test [fails](http://aspnetci/viewLog.html?buildId=422297&buildTypeId=XPlat_Linux_UbuntuUniverseCoreCLR) with this error:

```
The collection contained 2 matching element(s) instead of 1.
   at Microsoft.DotNet.Watcher.Tools.FunctionalTests.FileWatcherTests.<>c__DisplayClass8_0.<MultipleTriggers>b__0(String dir) in /_/test/dotnet-watch.FunctionalTests/FileWatcherTests.cs:line 333
   at Microsoft.DotNet.Watcher.Tools.FunctionalTests.FileWatcherTests.UsingTempDirectory(Action`1 action) in /_/test/dotnet-watch.FunctionalTests/FileWatcherTests.cs:line 428
```

**Comment by ryanbrandenburg** [comment]
Saw this again, [here's](http://aspnetci/httpAuth/app/rest/builds?locator=tag:FileWatcherWrong,sinceDate:201710010T000000-0001&fields=build(startDate,buildTypeId,status,branchName,webUrl,tags)) a list of these failures we've seen.

**Comment by natemcmaster** [comment]
Added more output to the test log. Let me know next time it fails. The log should have more info then.

**Comment by natemcmaster** [comment]
Thanks for investigating more. Looks like our test code is bad. Let's update the assertions to be less strict about how many events are raised.

**Comment by natemcmaster** [comment]
Should be fixed in https://github.com/aspnet/DotNetTools/pull/435. I'll keep an eye on CI for future failures.
