### ISSUE TITLE
Flaky tests: DeleteCompiledFile et al

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/DotNetTools#424]
These tests [fail](http://aspnetci/viewLog.html?buildId=441294&tab=buildResultsDiv&buildTypeId=XPlat_Mac_MacUniverseCoreCLR#testNameId-3939618593137135215) sometimes with the following error:
```
System.TimeoutException : The operation at /_/test/dotnet-watch.FunctionalTests/AwaitableProcess.cs:68 timed out after reaching the limit of 120000ms.
   at Microsoft.AspNetCore.Testing.TaskExtensions.TimeoutAfter[T](Task`1 task, TimeSpan timeout, String filePath, Int32 lineNumber)
   at Microsoft.DotNet.Watcher.Tools.FunctionalTests.AwaitableProcess.GetOutputLineAsync(String message, TimeSpan timeout) in /_/test/dotnet-watch.FunctionalTests/AwaitableProcess.cs:line 68
   at Microsoft.DotNet.Watcher.Tools.FunctionalTests.WatchableApp.StartWatcherAsync(String[] arguments, String name) in /_/test/dotnet-watch.FunctionalTests/Scenario/WatchableApp.cs:line 112
   at Microsoft.DotNet.Watcher.Tools.FunctionalTests.GlobbingAppTests.DeleteCompiledFile() in /_/test/dotnet-watch.FunctionalTests/GlobbingAppTests.cs:line 45
--- End of stack trace from previous location where exception was thrown ---
------- Stdout: -------
The temporary test folder is /Users/asplab/TeamCity/work/33bdfc1cae7b2a38/modules/DotNetTools/bin/dotnet-watch.FunctionalTests/Release/netcoreapp2.1/testWorkDir/b95cd847890d4639ade1ffe9eb296f78
Copying project /Users/asplab/TeamCity/work/33bdfc1cae7b2a38/modules/DotNetTools/bin/dotnet-watch.FunctionalTests/Release/netcoreapp2.1/TestProjects/GlobbingApp to /Users/asplab/TeamCity/work/33bdfc1cae7b2a38/modules/DotNetTools/bin/dotnet-watch.FunctionalTests/Release/netcoreapp2.1/testWorkDir/b95cd847890d4639ade1ffe9eb296f78/work/GlobbingApp
Restoring msbuild project in GlobbingApp
Project directory: '/Users/asplab/TeamCity/work/33bdfc1cae7b2a38/modules/DotNetTools/bin/dotnet-watch.FunctionalTests/Release/netcoreapp2.1/testWorkDir/b95cd847890d4639ade1ffe9eb296f78/work/GlobbingApp'
Started process 61178: /Users/asplab/TeamCity/work/33bdfc1cae7b2a38/.dotnet/dotnet restore
  Restoring packages for /Users/asplab/TeamCity/work/33bdfc1cae7b2a38/modules/DotNetTools/bin/dotnet-watch.FunctionalTests/Release/netcoreapp2.1/testWorkDir/b95cd847890d4639ade1ffe9eb296f78/work/GlobbingApp/GlobbingApp.csproj...
  Restore completed in 214.62 ms for /Users/asplab/TeamCity/work/33bdfc1cae7b2a38/modules/DotNetTools/bin/dotnet-watch.FunctionalTests/Release/netcoreapp2.1/testWorkDir/b95cd847890d4639ade1ffe9eb296f78/work/GlobbingApp/GlobbingApp.csproj.
```

Future instances of this failure can be tracked in the larger [timeout tag](http://aspnetci/httpAuth/app/rest/builds?locator=tag:timeout,sinceDate:201710010T000000-0001&fields=build(startDate,buildTypeId,status,branchName,webUrl,tags)).

**Comment by natemcmaster** [comment]
Dug into the logs more. This was fixed in https://github.com/aspnet/DotNetTools/pull/422.
