### ISSUE TITLE
Flaky tests: ChangeCompiledFile et al

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/DotNetTools#425]
This test [fails](http://aspnetci/viewLog.html?buildId=440978&buildTypeId=XPlat_Windows_Win10Universe&tab=buildResultsDiv) occasionally with the following error:
```
Waiting for output line [msg == 'Started']. Will wait for 120 sec.
4/4/2018 10:32:27 PM: post: 'watch : Started'
4/4/2018 10:32:27 PM: recv: 'watch : Started'
4/4/2018 10:32:29 PM: post: 'It was not possible to find any compatible framework version'
4/4/2018 10:32:29 PM: recv: 'It was not possible to find any compatible framework version'
4/4/2018 10:32:29 PM: post: 'The specified framework 'Microsoft.NETCore.App', version '2.1.0-preview3-26331-01' was not found.'
4/4/2018 10:32:29 PM: recv: 'The specified framework 'Microsoft.NETCore.App', version '2.1.0-preview3-26331-01' was not found.'
4/4/2018 10:32:29 PM: post: '  - Check application dependencies and target a framework version installed at:'
4/4/2018 10:32:29 PM: post: '      C:\BuildAgent\work\33bdfc1cae7b2a38\.dotnet\x64\'
4/4/2018 10:32:29 PM: post: '  - Installing .NET Core prerequisites might help resolve this problem:'
4/4/2018 10:32:29 PM: post: '      http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409'
4/4/2018 10:32:29 PM: post: '  - The .NET Core framework and SDK can be installed from:'
4/4/2018 10:32:29 PM: post: '      https://aka.ms/dotnet-download'
4/4/2018 10:32:29 PM: post: '  - The following versions are installed:'
4/4/2018 10:32:29 PM: recv: '  - Check application dependencies and target a framework version installed at:'
4/4/2018 10:32:29 PM: recv: '      C:\BuildAgent\work\33bdfc1cae7b2a38\.dotnet\x64\'
4/4/2018 10:32:29 PM: recv: '  - Installing .NET Core prerequisites might help resolve this problem:'
4/4/2018 10:32:29 PM: recv: '      http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409'
4/4/2018 10:32:29 PM: recv: '  - The .NET Core framework and SDK can be installed from:'
4/4/2018 10:32:29 PM: recv: '      https://aka.ms/dotnet-download'
4/4/2018 10:32:29 PM: recv: '  - The following versions are installed:'
4/4/2018 10:32:29 PM: post: '      2.0.0 at [C:\BuildAgent\work\33bdfc1cae7b2a38\.dotnet\x64\shared\Microsoft.NETCore.App]'
4/4/2018 10:32:29 PM: recv: '      2.0.0 at [C:\BuildAgent\work\33bdfc1cae7b2a38\.dotnet\x64\shared\Microsoft.NETCore.App]'
4/4/2018 10:32:29 PM: post: '      2.0.5 at [C:\BuildAgent\work\33bdfc1cae7b2a38\.dotnet\x64\shared\Microsoft.NETCore.App]'
4/4/2018 10:32:29 PM: recv: '      2.0.5 at [C:\BuildAgent\work\33bdfc1cae7b2a38\.dotnet\x64\shared\Microsoft.NETCore.App]'
4/4/2018 10:32:29 PM: post: '      2.1.0-preview2-26313-01 at [C:\BuildAgent\work\33bdfc1cae7b2a38\.dotnet\x64\shared\Microsoft.NETCore.App]'
4/4/2018 10:32:29 PM: post: '      2.1.0-preview2-26403-06 at [C:\BuildAgent\work\33bdfc1cae7b2a38\.dotnet\x64\shared\Microsoft.NETCore.App]'
4/4/2018 10:32:29 PM: recv: '      2.1.0-preview2-26313-01 at [C:\BuildAgent\work\33bdfc1cae7b2a38\.dotnet\x64\shared\Microsoft.NETCore.App]'
4/4/2018 10:32:29 PM: recv: '      2.1.0-preview2-26403-06 at [C:\BuildAgent\work\33bdfc1cae7b2a38\.dotnet\x64\shared\Microsoft.NETCore.App]'
4/4/2018 10:32:29 PM: post: 'watch : Exited with error code -2147450730'
4/4/2018 10:32:29 PM: recv: 'watch : Exited with error code -2147450730'
4/4/2018 10:32:29 PM: post: 'watch : Waiting for a file to change before restarting dotnet...'
4/4/2018 10:32:29 PM: recv: 'watch : Waiting for a file to change before restarting dotnet...'
Disposing WatchableApp
4/4/2018 10:34:26 PM: post: ''
4/4/2018 10:34:26 PM: post: ''
[22:40:38]	System.TimeoutException : The operation at C:\BuildAgent\work\33bdfc1cae7b2a38\modules\DotNetTools\test\dotnet-watch.FunctionalTests\AwaitableProcess.cs:68 timed out after reaching the limit of 120000ms.
[22:40:38]	   at Microsoft.AspNetCore.Testing.TaskExtensions.TimeoutAfter[T](Task`1 task, TimeSpan timeout, String filePath, Int32 lineNumber)
   at Microsoft.DotNet.Watcher.Tools.FunctionalTests.AwaitableProcess.GetOutputLineAsync(String message, TimeSpan timeout) in C:\BuildAgent\work\33bdfc1cae7b2a38\modules\DotNetTools\test\dotnet-watch.FunctionalTests\AwaitableProcess.cs:line 68
   at Microsoft.DotNet.Watcher.Tools.FunctionalTests.WatchableApp.StartWatcherAsync(String[] arguments, String name) in C:\BuildAgent\work\33bdfc1cae7b2a38\modules\DotNetTools\test\dotnet-watch.FunctionalTests\Scenario\WatchableApp.cs:line 112
   at Microsoft.DotNet.Watcher.Tools.FunctionalTests.GlobbingAppTests.ChangeCompiledFile(Boolean usePollingWatcher) in C:\BuildAgent\work\33bdfc1cae7b2a38\modules\DotNetTools\test\dotnet-watch.FunctionalTests\GlobbingAppTests.cs:line 28
--- End of stack trace from previous location where exception was thrown ---
```

It would appear that setting up the framework is not working for this test in some cases.

**Comment by ryanbrandenburg** [comment]
On second viewing this failed consistently during a specific period of time and was likely a resolved issue
