### ISSUE TITLE
Test failure: ChangeFileInDependency

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/DotNetTools#514]
This issue was made automatically. If there is a problem contact ryanbrandenburg.

This test [failed](http://aspnetci/viewLog.html?buildId=589955&buildTypeId=Releases_21Public_HighSierraOsxUniverse) with the following error:

```
System.TimeoutException : Process timed out after 60 seconds
   at Microsoft.DotNet.Watcher.Tools.FunctionalTests.ProjectToolScenario.ExecuteCommandAsync(String project, TimeSpan timeout, String[] arguments)
   at Microsoft.DotNet.Watcher.Tools.FunctionalTests.WatchableApp.PrepareAsync() in /_/test/dotnet-watch.FunctionalTests/Scenario/WatchableApp.cs:line 71
   at Microsoft.DotNet.Watcher.Tools.FunctionalTests.WatchableApp.StartWatcherAsync(String[] arguments, String name) in /_/test/dotnet-watch.FunctionalTests/Scenario/WatchableApp.cs:line 113
   at Microsoft.DotNet.Watcher.Tools.FunctionalTests.AppWithDepsTests.ChangeFileInDependency() in /_/test/dotnet-watch.FunctionalTests/AppWithDepsTests.cs:line 27
--- End of stack trace from previous location where exception was thrown ---
------- Stdout: -------
The temporary test folder is /Users/aspnetci/Documents/buildAgent/work/e37dd45d8cd1eaf4/modules/DotNetTools/bin/dotnet-watch.FunctionalTests/Release/netcoreapp2.1/tmp/jxdkwzcu.gsq
Copying project /Users/aspnetci/Documents/buildAgent/work/e37dd45d8cd1eaf4/modules/DotNetTools/bin/dotnet-watch.FunctionalTests/Release/netcoreapp2.1/TestProjects/AppWithDeps to /Users/aspnetci/Documents/buildAgent/work/e37dd45d8cd1eaf4/modules/DotNetTools/bin/dotnet-watch.FunctionalTests/Release/netcoreapp2.1/tmp/jxdkwzcu.gsq/AppWithDeps
Copying project /Users/aspnetci/Documents/buildAgent/work/e37dd45d8cd1eaf4/modules/DotNetTools/bin/dotnet-watch.FunctionalTests/Release/netcoreapp2.1/TestProjects/Dependency to /Users/aspnetci/Documents/buildAgent/work/e37dd45d8cd1eaf4/modules/DotNetTools/bin/dotnet-watch.FunctionalTests/Release/netcoreapp2.1/tmp/jxdkwzcu.gsq/Dependency
Restoring msbuild project in AppWithDeps
Project directory: '/Users/aspnetci/Documents/buildAgent/work/e37dd45d8cd1eaf4/modules/DotNetTools/bin/dotnet-watch.FunctionalTests/Release/netcoreapp2.1/tmp/jxdkwzcu.gsq/AppWithDeps'
Started process 86151: /Users/aspnetci/Documents/buildAgent/work/e37dd45d8cd1eaf4/.dotnet/dotnet restore
  Restoring packages for /Users/aspnetci/Documents/buildAgent/work/e37dd45d8cd1eaf4/modules/DotNetTools/bin/dotnet-watch.FunctionalTests/Release/netcoreapp2.1/tmp/jxdkwzcu.gsq/Dependency/Dependency.csproj...
  Restoring packages for /Users/aspnetci/Documents/buildAgent/work/e37dd45d8cd1eaf4/modules/DotNetTools/bin/dotnet-watch.FunctionalTests/Release/netcoreapp2.1/tmp/jxdkwzcu.gsq/AppWithDeps/AppWithDeps.csproj...
  Generating MSBuild file /Users/aspnetci/Documents/buildAgent/work/e37dd45d8cd1eaf4/modules/DotNetTools/bin/dotnet-watch.FunctionalTests/Release/netcoreapp2.1/tmp/jxdkwzcu.gsq/AppWithDeps/obj/AppWithDeps.csproj.nuget.g.props.
  Generating MSBuild file /Users/aspnetci/Documents/buildAgent/work/e37dd45d8cd1eaf4/modules/DotNetTools/bin/dotnet-watch.FunctionalTests/Release/netcoreapp2.1/tmp/jxdkwzcu.gsq/AppWithDeps/obj/AppWithDeps.csproj.nuget.g.targets.
  Generating MSBuild file /Users/aspnetci/Documents/buildAgent/work/e37dd45d8cd1eaf4/modules/DotNetTools/bin/dotnet-watch.FunctionalTests/Release/netcoreapp2.1/tmp/jxdkwzcu.gsq/Dependency/obj/Dependency.csproj.nuget.g.props.
  Generating MSBuild file /Users/aspnetci/Documents/buildAgent/work/e37dd45d8cd1eaf4/modules/DotNetTools/bin/dotnet-watch.FunctionalTests/Release/netcoreapp2.1/tmp/jxdkwzcu.gsq/Dependency/obj/Dependency.csproj.nuget.g.targets.
  Restore completed in 332.55 ms for /Users/aspnetci/Documents/buildAgent/work/e37dd45d8cd1eaf4/modules/DotNetTools/bin/dotnet-watch.FunctionalTests/Release/netcoreapp2.1/tmp/jxdkwzcu.gsq/AppWithDeps/AppWithDeps.csproj.
  Restore completed in 751.71 ms for /Users/aspnetci/Documents/buildAgent/work/e37dd45d8cd1eaf4/modules/DotNetTools/bin/dotnet-watch.FunctionalTests/Release/netcoreapp2.1/tmp/jxdkwzcu.gsq/Dependency/Dependency.csproj.
Process exited 86151
Process exited 86151 with code 0
Building AppWithDeps
Project directory: '/Users/aspnetci/Documents/buildAgent/work/e37dd45d8cd1eaf4/modules/DotNetTools/bin/dotnet-watch.FunctionalTests/Release/netcoreapp2.1/tmp/jxdkwzcu.gsq/AppWithDeps'
Started process 86175: /Users/aspnetci/Documents/buildAgent/work/e37dd45d8cd1eaf4/.dotnet/dotnet build
Microsoft (R) Build Engine version 15.9.19+g938f3292a0 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.
  Restore completed in 58.5 ms for /Users/aspnetci/Documents/buildAgent/work/e37dd45d8cd1eaf4/modules/DotNetTools/bin/dotnet-watch.FunctionalTests/Release/netcoreapp2.1/tmp/jxdkwzcu.gsq/Dependency/Dependency.csproj.
  Restore completed in 58.5 ms for /Users/aspnetci/Documents/buildAgent/work/e37dd45d8cd1eaf4/modules/DotNetTools/bin/dotnet-watch.FunctionalTests/Release/netcoreapp2.1/tmp/jxdkwzcu.gsq/AppWithDeps/AppWithDeps.csproj.
/Users/aspnetci/Documents/buildAgent/work/e37dd45d8cd1eaf4/.dotnet/sdk/2.1.500-preview-009398/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.RuntimeIdentifierInference.targets(143,5): message NETSDK1057: You are working with a preview version of the .NET Core SDK. You can define the SDK version via a global.json file in the current project. More at https://go.microsoft.com/fwlink/?linkid=869452 [/Users/aspnetci/Documents/buildAgent/work/e37dd45d8cd1eaf4/modules/DotNetTools/bin/dotnet-watch.FunctionalTests/Release/netcoreapp2.1/tmp/jxdkwzcu.gsq/AppWithDeps/AppWithDeps.csproj]
Killing process 86175
Disposing WatchableApp
```

Other tests within that build may have failed with a similar message, but they are not listed here. Check the link above for more info.

This test failed on 2.1.

CC Eilon

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact ryanbrandenburg.

Please use this workflow to address this flaky test issue, including checking applicable checkboxes and filling in the applicable "TODO" entries:

* Is this actually a flaky test?
  * No, this is a regular test failure, fix the test/product (TODO: Link to commit/PR)
  * Yes, proceed below...

* Is this test failure caused by product code flakiness? (Either this product, or another product this test depends on.)
  * [ ] File a bug against the product (TODO: Link to other bug)
  * Is it possible to change the test to avoid the flakiness?
    * Yes? Go to the "Change the test!" section.
    * No?
      * [ ] Disable the test (TODO: Link to PR/commit)
      * [ ] Wait for other bug to be resolved
      * [ ] Wait for us to get build that has the fix
      * [ ] Re-enable our test (TODO: Link to PR/commit)
      * [ ] Close this bug

* Is it that the test itself is flaky? This includes external transient problems (e.g. remote server problems, file system race condition, etc.)
  * Is there is a way to change our test to avoid this flakiness?
    * Yes? Change the test!
      * [ ] Change the test to avoid the flakiness, for example by using a different test strategy, or by adding retries w/ timeouts (TODO: Link to PR/commit)
      * [ ] Run the test 100 times locally as a sanity check.
      * [ ] Close this bug
    * No?
      * Is there any logging or extra information that we could add to make this more diagnosable when it happens again?
        * Yes?
            * [ ] Add the logging (TODO: Link to PR/commit)
        * No?
            * [ ] Delete the test because flaky tests are not useful (TODO: Link to PR/commit)

**Comment by Eilon** [comment]
@natemcmaster - enjoy.

cc @muratg FYI

**Comment by natemcmaster** [comment]
Time to backport all those 2.1 flaky test fixes, I suppose...

**Comment by Eilon** [comment]
@natemcmaster probably not the highest priority thing right now though.
